// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsLSYWRaBIP-z8hBXFfA5m8K0O1_VRxw0',
    appId: '1:269384199904:web:e1adb61c256ee3b58dea85',
    messagingSenderId: '269384199904',
    projectId: 'emotion-tracker-de685',
    authDomain: 'emotion-tracker-de685.firebaseapp.com',
    storageBucket: 'emotion-tracker-de685.appspot.com',
    measurementId: 'G-H9WXWTWEWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSaq9Puf_I7pJzXA-SoLu1_QEJK4PnzS0',
    appId: '1:269384199904:android:8aa1875c2fa9e3b48dea85',
    messagingSenderId: '269384199904',
    projectId: 'emotion-tracker-de685',
    storageBucket: 'emotion-tracker-de685.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB99p9Uk2HOnfDrscZAPcOVsJh2e_rWDUk',
    appId: '1:269384199904:ios:f13377a520a523198dea85',
    messagingSenderId: '269384199904',
    projectId: 'emotion-tracker-de685',
    storageBucket: 'emotion-tracker-de685.appspot.com',
    iosBundleId: 'com.example.emotionTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB99p9Uk2HOnfDrscZAPcOVsJh2e_rWDUk',
    appId: '1:269384199904:ios:7891527e773f50cd8dea85',
    messagingSenderId: '269384199904',
    projectId: 'emotion-tracker-de685',
    storageBucket: 'emotion-tracker-de685.appspot.com',
    iosBundleId: 'com.example.emotionTracker.RunnerTests',
  );
}
